-- ScheduledIssuance table for deferred batch mints.
-- Run once in the Supabase SQL editor (same project as the DAO / Token tables).

create table if not exists public."ScheduledIssuance" (
  id bigint generated by default as identity primary key,
  "createdAt" timestamptz not null default now(),
  environment text not null check (environment in ('dev', 'stg', 'production')),
  "sbtAddress" text not null,
  "to" text not null,
  -- Array of { "id": "1", "amount": "1" } objects (uint strings, same as batch-mint body)
  tokens jsonb not null,
  "executeAt" timestamptz not null,
  -- pending -> processing -> completed | failed; pending -> cancelled
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'failed', 'cancelled')),
  attempts integer not null default 0,
  "lastError" text,
  "mintTransactionHash" text,
  "mintBlockNumber" bigint,
  "processedAt" timestamptz
);

create index if not exists scheduled_issuance_due_idx
  on public."ScheduledIssuance" (status, "executeAt");

create index if not exists scheduled_issuance_environment_idx
  on public."ScheduledIssuance" (environment, "createdAt" desc);

-- If the table was created before stg support, widen the check constraint:
-- alter table public."ScheduledIssuance"
--   drop constraint "ScheduledIssuance_environment_check";
-- alter table public."ScheduledIssuance"
--   add constraint "ScheduledIssuance_environment_check"
--   check (environment in ('dev', 'stg', 'production'));
