export const CAMPAIGN_ABI = [
  {
    type: 'function',
    name: 'DAO_MANAGER_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addCampWinners',
    inputs: [
      { name: '_campaignId', type: 'uint256', internalType: 'uint256' },
      { name: '_addresses', type: 'address[]', internalType: 'address[]' },
      { name: '_gists', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'campGists',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'campGistsClaimed',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'campWinners',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'campWinnersClaimed',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'campaignId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'campaigns',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'sbtId', type: 'uint256', internalType: 'uint256' },
      { name: 'title', type: 'string', internalType: 'string' },
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'token', type: 'address', internalType: 'address' },
      {
        name: 'tokenType',
        type: 'uint8',
        internalType: 'enum Campaigns.TokenType',
      },
      { name: 'claimAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'totalAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'startDate', type: 'uint256', internalType: 'uint256' },
      { name: 'endDate', type: 'uint256', internalType: 'uint256' },
      { name: 'validateSignatures', type: 'bool', internalType: 'bool' },
      { name: 'creator', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimCampaign',
    inputs: [
      { name: '_campaignId', type: 'uint256', internalType: 'uint256' },
      { name: '_gist', type: 'bytes32', internalType: 'bytes32' },
      { name: '_message', type: 'string', internalType: 'string' },
      { name: '_signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createCampaign',
    inputs: [
      {
        name: '_campaign',
        type: 'tuple',
        internalType: 'struct Campaigns.Campaign',
        components: [
          { name: 'sbtId', type: 'uint256', internalType: 'uint256' },
          { name: 'title', type: 'string', internalType: 'string' },
          { name: 'description', type: 'string', internalType: 'string' },
          { name: 'token', type: 'address', internalType: 'address' },
          {
            name: 'tokenType',
            type: 'uint8',
            internalType: 'enum Campaigns.TokenType',
          },
          { name: 'claimAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'totalAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'startDate', type: 'uint256', internalType: 'uint256' },
          { name: 'endDate', type: 'uint256', internalType: 'uint256' },
          { name: 'validateSignatures', type: 'bool', internalType: 'bool' },
          { name: 'creator', type: 'address', internalType: 'address' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'daoFactory',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCreator',
    inputs: [{ name: '_campaignId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStatus',
    inputs: [{ name: '_campaignId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'uint8', internalType: 'enum Campaigns.Status' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_daoFactory', type: 'address', internalType: 'address' },
      {
        name: '_sbt',
        type: 'address',
        internalType: 'contract PEACECOINDAO_SBT',
      },
      {
        name: '_nft',
        type: 'address',
        internalType: 'contract PEACECOINDAO_NFT',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isWinner',
    inputs: [
      { name: '_campaignId', type: 'uint256', internalType: 'uint256' },
      { name: '_winner', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nft',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract PEACECOINDAO_NFT' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'onERC1155BatchReceived',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155Received',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'recoverERC20',
    inputs: [
      {
        name: '_token',
        type: 'address',
        internalType: 'contract ERC20Upgradeable',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sbt',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract PEACECOINDAO_SBT' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalClaimed',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'verify',
    inputs: [
      { name: '_signer', type: 'address', internalType: 'address' },
      { name: '_message', type: 'string', internalType: 'string' },
      { name: '_sig', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'event',
    name: 'CampWinnersAdded',
    inputs: [
      {
        name: 'campaignId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'winners',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CampWinnersClaimed',
    inputs: [
      {
        name: 'campaignId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'winner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CampaignCreated',
    inputs: [
      {
        name: 'campaignId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'sbtId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      { name: 'title', type: 'string', indexed: false, internalType: 'string' },
      {
        name: 'description',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'claimAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startDate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'validateSignatures',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'tokenType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum Campaigns.TokenType',
      },
      {
        name: 'token',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'creator',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'AlreadyDelegated', inputs: [] },
  { type: 'error', name: 'CampaignEnded', inputs: [] },
  { type: 'error', name: 'CampaignFullyClaimed', inputs: [] },
  { type: 'error', name: 'CampaignNotStarted', inputs: [] },
  { type: 'error', name: 'ContractDeploymentFailed', inputs: [] },
  { type: 'error', name: 'DAOAlreadyExists', inputs: [] },
  { type: 'error', name: 'DAODoesNotExist', inputs: [] },
  { type: 'error', name: 'DAONameAlreadyExists', inputs: [] },
  { type: 'error', name: 'EmptyNameNotAllowed', inputs: [] },
  { type: 'error', name: 'GovernanceTokenImplementationNotSet', inputs: [] },
  { type: 'error', name: 'GovernorImplementationNotSet', inputs: [] },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
  { type: 'error', name: 'InvalidAddress', inputs: [] },
  { type: 'error', name: 'InvalidAddressesLength', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidArrayLength', inputs: [] },
  { type: 'error', name: 'InvalidBalance', inputs: [] },
  { type: 'error', name: 'InvalidCampaign', inputs: [] },
  { type: 'error', name: 'InvalidCampaignId', inputs: [] },
  { type: 'error', name: 'InvalidClaimAmount', inputs: [] },
  { type: 'error', name: 'InvalidCommunityToken', inputs: [] },
  { type: 'error', name: 'InvalidCommunityTokenOwner', inputs: [] },
  { type: 'error', name: 'InvalidContributor', inputs: [] },
  { type: 'error', name: 'InvalidDAOManager', inputs: [] },
  { type: 'error', name: 'InvalidGistsLength', inputs: [] },
  { type: 'error', name: 'InvalidInitialization', inputs: [] },
  { type: 'error', name: 'InvalidMinter', inputs: [] },
  { type: 'error', name: 'InvalidName', inputs: [] },
  { type: 'error', name: 'InvalidPCEAddress', inputs: [] },
  { type: 'error', name: 'InvalidProposalState', inputs: [] },
  { type: 'error', name: 'InvalidQuorumVotes', inputs: [] },
  { type: 'error', name: 'InvalidRewardPerBlock', inputs: [] },
  { type: 'error', name: 'InvalidSignature', inputs: [] },
  { type: 'error', name: 'InvalidSignatureLength', inputs: [] },
  { type: 'error', name: 'InvalidStartDate', inputs: [] },
  { type: 'error', name: 'InvalidSymbol', inputs: [] },
  { type: 'error', name: 'InvalidTimelockDelay', inputs: [] },
  { type: 'error', name: 'InvalidTokenId', inputs: [] },
  { type: 'error', name: 'InvalidVotingDelay', inputs: [] },
  { type: 'error', name: 'InvalidVotingPeriod', inputs: [] },
  { type: 'error', name: 'InvalidWPCEAddress', inputs: [] },
  { type: 'error', name: 'NoUnusedTokens', inputs: [] },
  { type: 'error', name: 'NoWinners', inputs: [] },
  { type: 'error', name: 'NonTransferable', inputs: [] },
  { type: 'error', name: 'NotInitializing', inputs: [] },
  { type: 'error', name: 'NotWhitelisted', inputs: [] },
  { type: 'error', name: 'NothingToWithdraw', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'PermissionDenied', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'TimelockImplementationNotSet', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
]
