export const GOVERNOR_ABI = [
  {
    type: 'function',
    name: 'abdicate',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acceptAdmin',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchExecute',
    inputs: [
      { name: 'proposalIds', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'batchQueue',
    inputs: [
      { name: 'proposalIds', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancel',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'castVote',
    inputs: [
      { name: 'proposalId', type: 'uint256', internalType: 'uint256' },
      { name: 'support', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'execute',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'executeSetTimelockPendingAdmin',
    inputs: [
      { name: 'newPendingAdmin', type: 'address', internalType: 'address' },
      { name: 'eta', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getActions',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'targets', type: 'address[]', internalType: 'address[]' },
      { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'signatures', type: 'string[]', internalType: 'string[]' },
      { name: 'calldatas', type: 'bytes[]', internalType: 'bytes[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPastVotes',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'blockNumber', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getReceipt',
    inputs: [
      { name: 'proposalId', type: 'uint256', internalType: 'uint256' },
      { name: 'voter', type: 'address', internalType: 'address' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct GovernorAlpha.Receipt',
        components: [
          { name: 'hasVoted', type: 'bool', internalType: 'bool' },
          { name: 'support', type: 'bool', internalType: 'bool' },
          { name: 'votes', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSocialConfig',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IDAOFactory.SocialConfig',
        components: [
          { name: 'description', type: 'string', internalType: 'string' },
          { name: 'website', type: 'string', internalType: 'string' },
          { name: 'linkedin', type: 'string', internalType: 'string' },
          { name: 'twitter', type: 'string', internalType: 'string' },
          { name: 'telegram', type: 'string', internalType: 'string' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'guardian',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: 'daoName', type: 'string', internalType: 'string' },
      { name: 'tokenAddress', type: 'address', internalType: 'address' },
      { name: 'sbtAddress', type: 'address', internalType: 'address' },
      { name: 'nftAddress', type: 'address', internalType: 'address' },
      { name: 'timelockAddress', type: 'address', internalType: 'address' },
      { name: 'votingDelayBlocks', type: 'uint256', internalType: 'uint256' },
      { name: 'votingPeriodBlocks', type: 'uint256', internalType: 'uint256' },
      {
        name: 'proposalThresholdTokens',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'quorumVotesAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'guardianAddress', type: 'address', internalType: 'address' },
      {
        name: 'socialConfigInput',
        type: 'tuple',
        internalType: 'struct IDAOFactory.SocialConfig',
        components: [
          { name: 'description', type: 'string', internalType: 'string' },
          { name: 'website', type: 'string', internalType: 'string' },
          { name: 'linkedin', type: 'string', internalType: 'string' },
          { name: 'twitter', type: 'string', internalType: 'string' },
          { name: 'telegram', type: 'string', internalType: 'string' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initialized',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'latestProposalIds',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nft',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalMaxOperations',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalThreshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposals',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'eta', type: 'uint256', internalType: 'uint256' },
      { name: 'startBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'endBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'forVotes', type: 'uint256', internalType: 'uint256' },
      { name: 'againstVotes', type: 'uint256', internalType: 'uint256' },
      { name: 'canceled', type: 'bool', internalType: 'bool' },
      { name: 'executed', type: 'bool', internalType: 'bool' },
      { name: 'description', type: 'string', internalType: 'string' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'propose',
    inputs: [
      { name: 'targets', type: 'address[]', internalType: 'address[]' },
      { name: 'values', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'signatures', type: 'string[]', internalType: 'string[]' },
      { name: 'calldatas', type: 'bytes[]', internalType: 'bytes[]' },
      { name: 'description', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposer',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'queue',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'queueSetTimelockPendingAdmin',
    inputs: [
      { name: 'newPendingAdmin', type: 'address', internalType: 'address' },
      { name: 'eta', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'quorumVotes',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sbt',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'socialConfig',
    inputs: [],
    outputs: [
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'website', type: 'string', internalType: 'string' },
      { name: 'linkedin', type: 'string', internalType: 'string' },
      { name: 'twitter', type: 'string', internalType: 'string' },
      { name: 'telegram', type: 'string', internalType: 'string' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'state',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'enum GovernorAlpha.ProposalState',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'timelock',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract TimelockInterface' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updateGovernanceParameters',
    inputs: [
      { name: 'quorumVotes_', type: 'uint256', internalType: 'uint256' },
      { name: 'proposalThreshold_', type: 'uint256', internalType: 'uint256' },
      {
        name: 'proposalMaxOperations_',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateSocialConfig',
    inputs: [
      {
        name: 'newSocialConfig',
        type: 'tuple',
        internalType: 'struct IDAOFactory.SocialConfig',
        components: [
          { name: 'description', type: 'string', internalType: 'string' },
          { name: 'website', type: 'string', internalType: 'string' },
          { name: 'linkedin', type: 'string', internalType: 'string' },
          { name: 'twitter', type: 'string', internalType: 'string' },
          { name: 'telegram', type: 'string', internalType: 'string' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'votingDelay',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'votingPeriod',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ProposalCanceled',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      {
        name: 'proposer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'targets',
        type: 'address[]',
        indexed: false,
        internalType: 'address[]',
      },
      {
        name: 'values',
        type: 'uint256[]',
        indexed: false,
        internalType: 'uint256[]',
      },
      {
        name: 'signatures',
        type: 'string[]',
        indexed: false,
        internalType: 'string[]',
      },
      {
        name: 'calldatas',
        type: 'bytes[]',
        indexed: false,
        internalType: 'bytes[]',
      },
      {
        name: 'startBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalExecuted',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalMaxOperationsSet',
    inputs: [
      {
        name: 'oldProposalMaxOperations',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newProposalMaxOperations',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalQueued',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'eta', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalThresholdSet',
    inputs: [
      {
        name: 'oldProposalThreshold',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newProposalThreshold',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'QuorumVotesSet',
    inputs: [
      {
        name: 'oldQuorumVotes',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newQuorumVotes',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SocialConfigUpdated',
    inputs: [
      {
        name: 'description',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'website',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'linkedin',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'twitter',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'telegram',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoteCast',
    inputs: [
      {
        name: 'voter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'proposalId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      { name: 'support', type: 'bool', indexed: false, internalType: 'bool' },
      {
        name: 'votes',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
]
