export const MULTIPLE_VOTINGS_ABI = [
  {
    type: 'function',
    name: 'MAX_OPTIONS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_VOTING_DELAY',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_VOTING_PERIOD',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'admin',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancel',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'castMultipleChoiceVote',
    inputs: [
      { name: 'proposalId', type: 'uint256', internalType: 'uint256' },
      { name: 'selectedOption', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOptionVotes',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPastVotes',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'blockNumber', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposal',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'options', type: 'string[]', internalType: 'string[]' },
      { name: 'startBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'endBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'totalVotesCasted', type: 'uint256', internalType: 'uint256' },
      {
        name: 'state',
        type: 'uint8',
        internalType: 'enum MultipleVotings.ProposalState',
      },
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'hasVoted', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProposalState',
    inputs: [{ name: 'proposalId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'enum MultipleVotings.ProposalState',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_token', type: 'address', internalType: 'address' },
      { name: '_sbt', type: 'address', internalType: 'address' },
      { name: '_nft', type: 'address', internalType: 'address' },
      { name: '_votingDelay', type: 'uint256', internalType: 'uint256' },
      { name: '_votingPeriod', type: 'uint256', internalType: 'uint256' },
      { name: '_quorumVotes', type: 'uint256', internalType: 'uint256' },
      { name: '_proposalThreshold', type: 'uint256', internalType: 'uint256' },
      { name: '_admin', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'latestProposalIds',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nft',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalThreshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposals',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'proposer', type: 'address', internalType: 'address' },
      { name: 'startBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'endBlock', type: 'uint256', internalType: 'uint256' },
      { name: 'totalVotesCast', type: 'uint256', internalType: 'uint256' },
      { name: 'description', type: 'string', internalType: 'string' },
      {
        name: 'state',
        type: 'uint8',
        internalType: 'enum MultipleVotings.ProposalState',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposeMultipleChoice',
    inputs: [
      { name: 'options', type: 'string[]', internalType: 'string[]' },
      { name: 'description', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'quorumVotes',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sbt',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setAdmin',
    inputs: [{ name: '_admin', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setProposalThreshold',
    inputs: [
      { name: '_proposalThreshold', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setQuorumVotes',
    inputs: [
      { name: '_quorumVotes', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVotingDelay',
    inputs: [
      { name: '_votingDelay', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVotingPeriod',
    inputs: [
      { name: '_votingPeriod', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract GovernorTokenInterface',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'votingDelay',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'votingPeriod',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MultipleChoiceProposalCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      {
        name: 'proposer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'options',
        type: 'string[]',
        indexed: false,
        internalType: 'string[]',
      },
      {
        name: 'startBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MultipleChoiceVoteCast',
    inputs: [
      {
        name: 'voter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'proposalId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'selectedOption',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'availableVotes',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalCanceled',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProposalFinalized',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      {
        name: 'state',
        type: 'uint8',
        indexed: false,
        internalType: 'enum MultipleVotings.ProposalState',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'InvalidInitialization', inputs: [] },
  { type: 'error', name: 'NotInitializing', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
]
