export const STAKING_ABI = [
  {
    type: 'function',
    name: 'calculateApr',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToPeacecoin',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToWpeacecoin',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStakedPeacecoin',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: 'rewardPerBlockValue', type: 'uint256', internalType: 'uint256' },
      { name: 'pceAddress', type: 'address', internalType: 'address' },
      { name: 'wPceAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'lastUpdateBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pce',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeUnusedRewardPool',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rewardPerBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setRewardPerBlock',
    inputs: [
      { name: 'newRewardPerBlock', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stake',
    inputs: [
      { name: 'amountPeacecoin', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stakingReward',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalPool',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'wPce',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IWPCE' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'amountXPeacecoin', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RewardPerBlockUpdated',
    inputs: [
      {
        name: 'previousRewardPerBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newRewardPerBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'StakedPEACECOIN',
    inputs: [
      {
        name: 'amountPeacecoin',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountxPeacecoin',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'UnusedRewardPoolRevoked',
    inputs: [
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WithdrawnPEACECOIN',
    inputs: [
      {
        name: 'amountPeacecoin',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountxPeacecoin',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'AlreadyDelegated', inputs: [] },
  { type: 'error', name: 'CampaignEnded', inputs: [] },
  { type: 'error', name: 'CampaignFullyClaimed', inputs: [] },
  { type: 'error', name: 'CampaignNotStarted', inputs: [] },
  { type: 'error', name: 'ContractDeploymentFailed', inputs: [] },
  { type: 'error', name: 'DAOAlreadyExists', inputs: [] },
  { type: 'error', name: 'DAODoesNotExist', inputs: [] },
  { type: 'error', name: 'DAONameAlreadyExists', inputs: [] },
  { type: 'error', name: 'EmptyNameNotAllowed', inputs: [] },
  { type: 'error', name: 'GovernanceTokenImplementationNotSet', inputs: [] },
  { type: 'error', name: 'GovernorImplementationNotSet', inputs: [] },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
  { type: 'error', name: 'InvalidAddress', inputs: [] },
  { type: 'error', name: 'InvalidAddressesLength', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'InvalidArrayLength', inputs: [] },
  { type: 'error', name: 'InvalidBalance', inputs: [] },
  { type: 'error', name: 'InvalidCampaign', inputs: [] },
  { type: 'error', name: 'InvalidCampaignId', inputs: [] },
  { type: 'error', name: 'InvalidClaimAmount', inputs: [] },
  { type: 'error', name: 'InvalidCommunityToken', inputs: [] },
  { type: 'error', name: 'InvalidCommunityTokenOwner', inputs: [] },
  { type: 'error', name: 'InvalidContributor', inputs: [] },
  { type: 'error', name: 'InvalidCreator', inputs: [] },
  { type: 'error', name: 'InvalidGistsLength', inputs: [] },
  { type: 'error', name: 'InvalidInitialization', inputs: [] },
  { type: 'error', name: 'InvalidMinter', inputs: [] },
  { type: 'error', name: 'InvalidName', inputs: [] },
  { type: 'error', name: 'InvalidPCEAddress', inputs: [] },
  { type: 'error', name: 'InvalidProposalState', inputs: [] },
  { type: 'error', name: 'InvalidQuorumVotes', inputs: [] },
  { type: 'error', name: 'InvalidRewardPerBlock', inputs: [] },
  { type: 'error', name: 'InvalidSignature', inputs: [] },
  { type: 'error', name: 'InvalidSignatureLength', inputs: [] },
  { type: 'error', name: 'InvalidStartDate', inputs: [] },
  { type: 'error', name: 'InvalidSymbol', inputs: [] },
  { type: 'error', name: 'InvalidTimelockDelay', inputs: [] },
  { type: 'error', name: 'InvalidTokenId', inputs: [] },
  { type: 'error', name: 'InvalidVotingDelay', inputs: [] },
  { type: 'error', name: 'InvalidVotingPeriod', inputs: [] },
  { type: 'error', name: 'InvalidWPCEAddress', inputs: [] },
  { type: 'error', name: 'InvalidateDaoManager', inputs: [] },
  { type: 'error', name: 'MultipleVotingImplementationNotSet', inputs: [] },
  { type: 'error', name: 'NoUnusedTokens', inputs: [] },
  { type: 'error', name: 'NoWinners', inputs: [] },
  { type: 'error', name: 'NonTransferable', inputs: [] },
  { type: 'error', name: 'NotInitializing', inputs: [] },
  { type: 'error', name: 'NotWhitelisted', inputs: [] },
  { type: 'error', name: 'NothingToWithdraw', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'PermissionDenied', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'TimelockImplementationNotSet', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
]
