name: ci

on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22.4.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Type check
        run: npm run tsc

      - name: Format check
        run: npm run format

      - name: Lint
        run: npm run lint
