name: ci

on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.1.x'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Type check
        run: yarn tsc

      - name: Format check
        run: yarn format

      - name: Lint
        run: yarn lint
